import type { Location } from "./types"

// Curated list of global locations for the game
// In production, these would use actual 360-degree panoramic images
export const LOCATIONS: Location[] = [
  {
    id: "eiffel-tower",
    name: "Eiffel Tower",
    country: "France",
    continent: "Europe",
    lat: 48.8584,
    lng: 2.2945,
    panoramaUrl: "https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=1200&h=600&fit=crop",
    difficulty: "easy",
    hints: ["Famous iron tower", "City of lights", "European capital"],
  },
  {
    id: "times-square",
    name: "Times Square",
    country: "United States",
    continent: "North America",
    lat: 40.758,
    lng: -73.9855,
    panoramaUrl: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=1200&h=600&fit=crop",
    difficulty: "easy",
    hints: ["Bright screens and advertisements", "The Big Apple", "Broadway nearby"],
  },
  {
    id: "great-wall",
    name: "Great Wall of China",
    country: "China",
    continent: "Asia",
    lat: 40.4319,
    lng: 116.5704,
    panoramaUrl: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=1200&h=600&fit=crop",
    difficulty: "medium",
    hints: ["Ancient defense structure", "Visible from space myth", "Eastern dynasty"],
  },
  {
    id: "christ-redeemer",
    name: "Christ the Redeemer",
    country: "Brazil",
    continent: "South America",
    lat: -22.9519,
    lng: -43.2105,
    panoramaUrl: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=1200&h=600&fit=crop",
    difficulty: "medium",
    hints: ["Art Deco statue", "Mountain peak view", "Carnival city"],
  },
  {
    id: "colosseum",
    name: "Colosseum",
    country: "Italy",
    continent: "Europe",
    lat: 41.8902,
    lng: 12.4922,
    panoramaUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=1200&h=600&fit=crop",
    difficulty: "easy",
    hints: ["Ancient amphitheater", "Gladiator battles", "Eternal city"],
  },
  {
    id: "taj-mahal",
    name: "Taj Mahal",
    country: "India",
    continent: "Asia",
    lat: 27.1751,
    lng: 78.0421,
    panoramaUrl: "https://images.unsplash.com/photo-1564507592333-c60d0d94add1?w=1200&h=600&fit=crop",
    difficulty: "easy",
    hints: ["White marble mausoleum", "Monument of love", "Mughal architecture"],
  },
  {
    id: "machu-picchu",
    name: "Machu Picchu",
    country: "Peru",
    continent: "South America",
    lat: -13.1631,
    lng: -72.545,
    panoramaUrl: "https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=1200&h=600&fit=crop",
    difficulty: "medium",
    hints: ["Ancient Incan citadel", "Mountain ruins", "Lost city"],
  },
  {
    id: "sydney-opera",
    name: "Sydney Opera House",
    country: "Australia",
    continent: "Oceania",
    lat: -33.8568,
    lng: 151.2153,
    panoramaUrl: "https://images.unsplash.com/photo-1523059623039-a9ed027e7fad?w=1200&h=600&fit=crop",
    difficulty: "easy",
    hints: ["Sail-like architecture", "Harbor location", "Southern hemisphere"],
  },
  {
    id: "pyramids-giza",
    name: "Pyramids of Giza",
    country: "Egypt",
    continent: "Africa",
    lat: 29.9792,
    lng: 31.1342,
    panoramaUrl: "https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=1200&h=600&fit=crop",
    difficulty: "easy",
    hints: ["Ancient wonders", "Desert monuments", "Pharaoh tombs"],
  },
  {
    id: "santorini",
    name: "Santorini",
    country: "Greece",
    continent: "Europe",
    lat: 36.3932,
    lng: 25.4615,
    panoramaUrl: "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=1200&h=600&fit=crop",
    difficulty: "medium",
    hints: ["White and blue buildings", "Volcanic island", "Aegean Sea"],
  },
  {
    id: "mount-fuji",
    name: "Mount Fuji",
    country: "Japan",
    continent: "Asia",
    lat: 35.3606,
    lng: 138.7278,
    panoramaUrl: "https://images.unsplash.com/photo-1576675784201-9710f3460c4f?w=1200&h=600&fit=crop",
    difficulty: "medium",
    hints: ["Iconic volcano", "Snow-capped peak", "Cherry blossoms"],
  },
  {
    id: "victoria-falls",
    name: "Victoria Falls",
    country: "Zimbabwe/Zambia",
    continent: "Africa",
    lat: -17.9243,
    lng: 25.8572,
    panoramaUrl: "https://images.unsplash.com/photo-1546514355-7fdc90ccbd03?w=1200&h=600&fit=crop",
    difficulty: "hard",
    hints: ["Massive waterfall", "The Smoke that Thunders", "Border location"],
  },
  {
    id: "big-ben",
    name: "Big Ben",
    country: "United Kingdom",
    continent: "Europe",
    lat: 51.5007,
    lng: -0.1246,
    panoramaUrl: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200&h=600&fit=crop",
    difficulty: "easy",
    hints: ["Clock tower", "Westminster", "Royal city"],
  },
  {
    id: "golden-gate",
    name: "Golden Gate Bridge",
    country: "United States",
    continent: "North America",
    lat: 37.8199,
    lng: -122.4783,
    panoramaUrl: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=1200&h=600&fit=crop",
    difficulty: "easy",
    hints: ["Orange suspension bridge", "Foggy city", "West coast"],
  },
  {
    id: "petra",
    name: "Petra",
    country: "Jordan",
    continent: "Asia",
    lat: 30.3285,
    lng: 35.4444,
    panoramaUrl: "https://images.unsplash.com/photo-1578922746158-b712e3750ff4?w=1200&h=600&fit=crop",
    difficulty: "hard",
    hints: ["Rose-red city", "Rock-cut architecture", "Ancient Nabataean"],
  },
]

// Get random locations for a game round
export function getRandomLocations(count: number): Location[] {
  const shuffled = [...LOCATIONS].sort(() => Math.random() - 0.5)
  const selected = shuffled.slice(0, Math.min(count, LOCATIONS.length))
  return selected
}

// Get location by ID
export function getLocationById(id: string): Location | undefined {
  return LOCATIONS.find((loc: Location) => loc.id === id)
}
